config/routes.rb
Demo::Application.routes.draw do

  root:to => 'today#index'
  devise_for :users

  get "say/hello"

  get "say/goodbye"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time=Time.now
  end

  def goodbye
  	@files =Dir.glob("*")
  end
  def getFiles
  	
  end
end

app/controllers/today_controller.rb
class TodayController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/today_helper.rb
module TodayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert>"<%= alert %></p>
<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<h1>Goodbye!</h1>
<p>it was nice have you here</p>
<p>Say<a href="/say/hello">Hello</a></p>
<p>
<%=link_to "Hello",say_hello_path %>again
</p>
<h3>My test code</h3>
1+2=<%=1+2 %><br>
"caw"+"boy"--><%="caw"+"boy"%><br>
one hour express :<%= 1.hour.from_now%><br>
all file list:<%=@files%>
<br>
<% for file in @files%>
	file name is :<%=file%><br>
<% end %>
<p>Find me in app/views/say/goodbye.html.erb</p>

app/views/say/hello.html.erb
<h1>Say#hello</h1>
<h2>Hello from Rails !</h2>
<p>It is now <%=Time.now %></p>
<p>This time is <%=@time %></p>
<p>Say<a href="/say/goodbye">Goodbye</a></p>
<p>
	Time to say 
	<%= link_to "Goodbye",say_goodbye_path %>!
</p>
<p>Find me in app/views/say/hello.html.erb</p>

app/views/today/index.html.erb
<h1>Today#index</h1>
<p>devise插件测试</p>
<%if user_signed_in?%>
<%= current_user.email%><br />
<%= link_to "登出", destroy_user_session_path, :method => :delete %><br />
<% else%>
<!-- div#header>ul.navigation>li*4>a -->
<div id="d1">
	<ul class="u1">
		<li><a href=""></a>你好</li>
		<li><a href=""></a></li>
		<li><a href=""></a></li>
		<li><a href=""></a></li>
	</ul>
</div>

<!--zcoding table#t1>td*4>tr*4 -->
<p></p>
<%= link_to '注册',new_user_registration_path %> or <%= link_to '登录',new_user_session_path %>
<% end %>